meta:
  schema_version: 3
hosts:
  all:
    - ssh_target: root@c-lon-1.sikademo.com
      vars:
        i: 1
        ip: 206.189.62.235
    - ssh_target: root@c-lon-2.sikademo.com
      vars:
        i: 2
        ip: 165.232.115.48
    - ssh_target: root@c-lon-3.sikademo.com
      vars:
        i: 3
        ip: 209.38.216.171
plays:
  - name:  Setup systemd service c-lon-{1,2,3}
    hosts: [all]
    tasks:
      - name: Mkdirs
        command:
          cmd: mkdir -p /etc/consul && mkdir -p /var/lib/consul
      - name: Systemd service
        template:
          path: /etc/systemd/system/consul.service
          template: |
            [Unit]
            ConditionPathExists=/var/lib/consul
            After=network.target

            [Service]
            Type=simple
            User=root
            Group=root
            WorkingDirectory=/var/lib/consul

            ExecStart=consul agent -config-dir=/etc/consul
            Restart=on-failure
            RestartSec=10

            [Install]
            WantedBy=multi-user.target
      - name: Add systemd service
        command:
          cmd: systemctl daemon-reload && systemctl enable consul
  - name:  Setup consul
    hosts: [all]
    tags: [consul]
    tasks:
      - name: Config
        template:
          path: /etc/consul/consul.hcl
          template: |
            {
              "bootstrap_expect": 3,
              "ui_config": {
                "enabled": true,
              },
              "client_addr": "0.0.0.0",
              "datacenter": "lon",
              "data_dir": "/var/lib/consul",
              "rejoin_after_leave": true,
              "server": true,
              "bind_addr": "{{ .Vars.ip }}",
              "retry_join": ["206.189.62.235", "165.232.115.48", "209.38.216.171"]
              "retry_join_wan": [
                "c-fra-1.sikademo.com",
                "c-fra-2.sikademo.com",
                "c-fra-3.sikademo.com",
                "reg1.sikademo.com",
                "reg2.sikademo.com"
              ]
            }
      - name: Restart consul
        command:
          cmd: systemctl restart consul
